package alteon

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

// Generierte Flat-Specs fuer den Umbau aller Bestandsressourcen.
// Felder gegen echte Geraete-GETs verifiziert (Datei "zwi" + VirtService 711).
// Command-Felder (Add*/Rem*/Delete*/Copy*) und Bitmap-Felder (Rule, UrlBmap,
// PortsIngress/Egress) sind bewusst ausgeschlossen; sie koennen spaeter als
// deklarative Sets ergaenzt werden (wie bei server_group servers, PIP ports).

func http2PolicySpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_http2_policy",
		Tables:       []string{"SlbNewAcclCfgHttp2PolTable"},
		KeySchema:    "nameidindex",
		KeyType:      ftString,
		KeyAPIs:      []string{"NameIdIndex"},
		Fields: []flatField{
			{"name", "Name", ftString},
			{"admin_status", "AdminStatus", ftInt},
			{"streams", "Streams", ftInt},
			{"idle", "Idle", ftInt},
			{"ena_insert", "EnaInsert", ftInt},
			{"header", "Header", ftString},
			{"ena_server_push", "EnaServerPush", ftInt},
			{"hpack_size", "HpackSize", ftString},
			{"backend_status", "BackendStatus", ftInt},
			{"backend_streams", "BackendStreams", ftInt},
			{"backend_hpack_size", "BackendHpackSize", ftString},
		},
	}
}
func resource_alteon_http2_policy() *schema.Resource {
	return flatResourceFromSpec(http2PolicySpec())
}

func sslPolicySpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_ssl_policy",
		Tables:       []string{"SlbNewSslCfgSSLPolTable"},
		KeySchema:    "nameidindex",
		KeyType:      ftString,
		KeyAPIs:      []string{"NameIdIndex"},
		Fields: []flatField{
			{"name", "Name", ftString},
			{"pass_info_cipher_name", "PassInfoCipherName", ftString},
			{"pass_info_cipher_flag", "PassInfoCipherFlag", ftInt},
			{"pass_info_version_name", "PassInfoVersionName", ftString},
			{"pass_info_version_flag", "PassInfoVersionFlag", ftInt},
			{"pass_info_head_bits_name", "PassInfoHeadBitsName", ftString},
			{"pass_info_head_bits_flag", "PassInfoHeadBitsFlag", ftInt},
			{"pass_info_frontend", "PassInfoFrontend", ftInt},
			{"cipher_name", "CipherName", ftInt},
			{"cipher_userdef", "CipherUserdef", ftString},
			{"intermca_chain_name", "IntermcaChainName", ftString},
			{"intermca_chain_type", "IntermcaChainType", ftString},
			{"becipher", "Becipher", ftInt},
			{"authpol", "Authpol", ftString},
			{"convuri", "Convuri", ftString},
			{"bessl", "Bessl", ftInt},
			{"convert", "Convert", ftInt},
			{"admin_status", "AdminStatus", ftInt},
			{"pass_info_comply", "PassInfoComply", ftInt},
			{"fessl", "Fessl", ftInt},
			{"fe_sslv3_version", "FESslv3Version", ftInt},
			{"fe_tls10_version", "FETls10Version", ftInt},
			{"fe_tls11_version", "FETls11Version", ftInt},
			{"be_sslv3_version", "BESslv3Version", ftInt},
			{"be_tls10_version", "BETls10Version", ftInt},
			{"be_tls11_version", "BETls11Version", ftInt},
			{"fe_tls12_version", "FETls12Version", ftInt},
			{"be_tls12_version", "BETls12Version", ftInt},
			{"cipher_expert_userdef", "CipherExpertUserdef", ftString},
			{"be_cipher_userdef", "BeCipherUserdef", ftString},
			{"be_cipher_expert_userdef", "BeCipherExpertUserdef", ftString},
			{"be_client_cert_name", "BEClientCertName", ftString},
			{"be_trusted_c_acert_name", "BETrustedCAcertName", ftString},
			{"be_trusted_c_acert_type", "BETrustedCAcertType", ftString},
			{"secreneg", "Secreneg", ftString},
			{"d_hkey", "DHkey", ftInt},
			{"be_authpol", "BEAuthpol", ftString},
			{"hwoffld_fe_rsa", "HwoffldFeRsa", ftInt},
			{"hwoffld_fe_dh", "HwoffldFeDh", ftInt},
			{"hwoffld_fe_ec", "HwoffldFeEc", ftInt},
			{"hwoffld_fe_bulk", "HwoffldFeBulk", ftInt},
			{"hwoffld_fe_pkey", "HwoffldFePkey", ftInt},
			{"hwoffld_fe_features", "HwoffldFeFeatures", ftInt},
			{"hwoffld_be_rsa", "HwoffldBeRsa", ftInt},
			{"hwoffld_be_dh", "HwoffldBeDh", ftInt},
			{"hwoffld_be_ec", "HwoffldBeEc", ftInt},
			{"hwoffld_be_bulk", "HwoffldBeBulk", ftInt},
			{"hwoffld_be_pkey", "HwoffldBePkey", ftInt},
			{"hwoffld_be_features", "HwoffldBeFeatures", ftInt},
			{"besni", "Besni", ftInt},
			{"fe_tls13_version", "FETls13Version", ftInt},
			{"be_tls13_version", "BETls13Version", ftInt},
			{"ssl_pol0_rttfe_data", "SSLPol0RTTFEData", ftInt},
			{"fe_reuse_state", "FeReuseState", ftInt},
			{"be_reuse_state", "BeReuseState", ftInt},
			{"be_reuse_src_match", "BeReuseSrcMatch", ftInt},
			{"be_reuse_ticket", "BeReuseTicket", ftInt},
			{"fe_reuse_ticket", "FeReuseTicket", ftInt},
			{"fe_gm_ssl_version", "FEGmSslVersion", ftString},
			{"be_gm_ssl_version", "BEGmSslVersion", ftString},
			{"fe_gm_ssl_priority", "FEGmSslPriority", ftString},
			{"fe_sslsigs", "FESslsigs", ftString},
			{"be_sslsigs", "BESslsigs", ftString},
			{"fe_sslgroups", "FESslgroups", ftString},
			{"be_sslgroups", "BESslgroups", ftString},
			{"hs_tmout", "HSTmout", ftInt},
			{"dest_host", "DestHost", ftString},
			{"dest_port", "DestPort", ftInt},
		},
	}
}
func resource_alteon_ssl_policy() *schema.Resource {
	return flatResourceFromSpec(sslPolicySpec())
}

func virtualServerSpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_virtual_server",
		Tables:       []string{"SlbNewCfgEnhVirtServerTable"},
		KeySchema:    "index",
		KeyType:      ftString,
		KeyAPIs:      []string{"VirtServerIndex"},
		Fields: []flatField{
			{"virt_server_ip_address", "VirtServerIpAddress", ftString},
			{"virt_server_layer3_only", "VirtServerLayer3Only", ftInt},
			{"virt_server_state", "VirtServerState", ftInt},
			{"virt_server_dname", "VirtServerDname", ftString},
			{"virt_server_bwm_contract", "VirtServerBwmContract", ftInt},
			{"virt_server_weight", "VirtServerWeight", ftInt},
			{"virt_server_avail", "VirtServerAvail", ftInt},
			{"virt_server_vname", "VirtServerVname", ftString},
			{"virt_server_ip_ver", "VirtServerIpVer", ftInt},
			{"virt_server_ipv6_addr", "VirtServerIpv6Addr", ftString},
			{"virt_server_free_service_idx", "VirtServerFreeServiceIdx", ftInt},
			{"virt_server_c_reset", "VirtServerCReset", ftInt},
			{"virt_server_src_network", "VirtServerSrcNetwork", ftString},
			{"virt_server_nat", "VirtServerNat", ftString},
			{"virt_server_nat6", "VirtServerNat6", ftString},
			{"virt_server_is_dns_sec_vip", "VirtServerIsDnsSecVip", ftInt},
			{"virt_server_avail_persist", "VirtServerAvailPersist", ftInt},
			{"virt_server_wanlink", "VirtServerWanlink", ftString},
			{"virt_server_rt_src_mac", "VirtServerRtSrcMac", ftInt},
			{"virt_server_creation_type", "VirtServerCreationType", ftInt},
			{"virt_serverdad", "VirtServerdad", ftInt},
			{"virt_server_segment", "VirtServerSegment", ftString},
		},
	}
}
func resource_alteon_virtual_server() *schema.Resource {
	return flatResourceFromSpec(virtualServerSpec())
}

func realServerSpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_real_server",
		Tables:       []string{"SlbNewCfgEnhRealServerTable", "SlbNewCfgEnhRealServerSecondPartTable", "SlbNewCfgEnhRealServerThirdPartTable"},
		KeySchema:    "index",
		KeyType:      ftString,
		KeyAPIs:      []string{"Index"},
		Fields: []flatField{
			{"ip_addr", "IpAddr", ftString},
			{"weight", "Weight", ftInt},
			{"max_conns", "MaxConns", ftInt},
			{"time_out", "TimeOut", ftInt},
			{"ping_interval", "PingInterval", ftInt},
			{"fail_retry", "FailRetry", ftInt},
			{"succ_retry", "SuccRetry", ftInt},
			{"state", "State", ftInt},
			{"type", "Type", ftInt},
			{"name", "Name", ftString},
			{"cookie", "Cookie", ftInt},
			{"exclude_str", "ExcludeStr", ftInt},
			{"submac", "Submac", ftInt},
			{"idsport", "Idsport", ftInt},
			{"ip_ver", "IpVer", ftInt},
			{"ipv6_addr", "Ipv6Addr", ftString},
			{"nxt_rport_idx", "NxtRportIdx", ftInt},
			{"nxt_buddy_idx", "NxtBuddyIdx", ftInt},
			{"llb_type", "LLBType", ftInt},
			{"vlan_ingress", "VlanIngress", ftInt},
			{"vlan_egress", "VlanEgress", ftInt},
			{"egress_if", "EgressIf", ftInt},
			{"sec_type", "SecType", ftInt},
			{"ingress_if", "IngressIf", ftInt},
			{"sec_device_flag", "SecDeviceFlag", ftInt},
			{"ingport", "Ingport", ftInt},
			{"proxy", "Proxy", ftInt},
			{"ldapwr", "Ldapwr", ftInt},
			{"idsvlan", "Idsvlan", ftInt},
			{"avail", "Avail", ftInt},
			{"fast_health_check", "FastHealthCheck", ftInt},
			{"subdmac", "Subdmac", ftInt},
			{"overflow", "Overflow", ftInt},
			{"bkp_preempt", "BkpPreempt", ftInt},
			{"mode", "Mode", ftInt},
			{"proxy_ip_mode", "ProxyIpMode", ftInt},
			{"proxy_ip_addr", "ProxyIpAddr", ftString},
			{"proxy_ip_mask", "ProxyIpMask", ftString},
			{"proxy_ipv6_addr", "ProxyIpv6Addr", ftString},
			{"proxy_ipv6_prefix", "ProxyIpv6Prefix", ftInt},
			{"proxy_ip_persistency", "ProxyIpPersistency", ftInt},
			{"proxy_ip_n_wclass", "ProxyIpNWclass", ftString},
			{"proxy_ip_n_wclass_persistency", "ProxyIpNWclassPersistency", ftInt},
			{"ingvlan", "Ingvlan", ftInt},
			{"oid", "Oid", ftString},
			{"comm_string", "CommString", ftString},
			{"back_up", "BackUp", ftString},
			{"health_id", "HealthID", ftString},
			{"critical_conn_thrsh", "CriticalConnThrsh", ftInt},
			{"high_conn_thrsh", "HighConnThrsh", ftInt},
			{"upload_band_width", "UploadBandWidth", ftInt},
			{"download_band_width", "DownloadBandWidth", ftInt},
		},
	}
}
func resource_alteon_real_server() *schema.Resource {
	return flatResourceFromSpec(realServerSpec())
}

func virtualServiceSpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_virtual_service",
		Tables: []string{
			"SlbNewCfgEnhVirtServicesTable",
			"SlbNewCfgEnhVirtServicesSecondPartTable",
			"SlbNewCfgEnhVirtServicesThirdPartTable",
			"SlbNewCfgEnhVirtServicesFourthPartTable",
			"SlbNewCfgEnhVirtServicesFifthPartTable",
			"SlbNewCfgEnhVirtServicesSixthPartTable",
			"SlbNewCfgEnhVirtServicesSeventhPartTable",
		},
		KeySchema:   "servindex",
		KeyType:     ftString,
		KeyAPIs:     []string{"ServIndex", "Index"},
		Key2Schema:  "index",
		Key2API:     "Index",
		Key2Type:    ftInt,
		PartKeyAPIs: []string{"ServSecondPartIndex", "SecondPartIndex", "ServThirdPartIndex", "ThirdPartIndex", "ServFourthPartIndex", "FourthPartIndex", "ServFifthPartIndex", "FifthPartIndex", "ServSixthPartIndex", "SixthPartIndex", "ServSeventhPartIndex", "SeventhPartIndex"},
		Fields: []flatField{
			{"virt_port", "VirtPort", ftInt},
			{"real_port", "RealPort", ftInt},
			{"udp_balance", "UDPBalance", ftInt},
			{"bwm_contract", "BwmContract", ftInt},
			{"dir_server_rtn", "DirServerRtn", ftInt},
			{"rtsp_url_parse", "RtspUrlParse", ftInt},
			{"d_bind", "DBind", ftInt},
			{"ftp_parsing", "FtpParsing", ftInt},
			{"remap_udp_frags", "RemapUDPFrags", ftInt},
			{"dns_slb", "DnsSlb", ftInt},
			{"response_count", "ResponseCount", ftInt},
			{"p_bind", "PBind", ftInt},
			{"coffset", "Coffset", ftInt},
			{"clength", "Clength", ftInt},
			{"uri_cookie", "UriCookie", ftInt},
			{"cookie_mode", "CookieMode", ftInt},
			{"http_slb", "HttpSlb", ftInt},
			{"http_slb_option", "HttpSlbOption", ftInt},
			{"http_slb2", "HttpSlb2", ftInt},
			{"apm", "Apm", ftInt},
			{"non_http", "NonHTTP", ftInt},
			{"ip_rep", "IpRep", ftInt},
			{"cdn_proxy", "CdnProxy", ftInt},
			{"status", "Status", ftInt},
			{"rt_src_tnl", "RtSrcTnl", ftInt},
			{"connmgt_status", "ConnmgtStatus", ftInt},
			{"connmgt_timeout", "ConnmgtTimeout", ftInt},
			{"cachepol", "Cachepol", ftString},
			{"comppol", "Comppol", ftString},
			{"ss_lpol", "SSLpol", ftString},
			{"serv_cert", "ServCert", ftString},
			{"httpmod_list", "HttpmodList", ftString},
			{"cloaksrv", "Cloaksrv", ftInt},
			{"serv_errcode_status", "ServErrcodeStatus", ftInt},
			{"serv_errcode_match", "ServErrcodeMatch", ftString},
			{"serv_errcode_http_redir", "ServErrcodeHttpRedir", ftInt},
			{"serv_errcode_url", "ServErrcodeUrl", ftString},
			{"serv_errcode", "ServErrcode", ftString},
			{"serv_errcode_new", "ServErrcodeNew", ftString},
			{"serv_errcode_reason", "ServErrcodeReason", ftString},
			{"serv_urlchang_status", "ServUrlchangStatus", ftInt},
			{"serv_urlchang_host_type", "ServUrlchangHostType", ftInt},
			{"fe_tcp_pol_id", "FeTcpPolId", ftString},
			{"be_tcp_pol_id", "BeTcpPolId", ftString},
			{"basic_connmgt_status", "BasicConnmgtStatus", ftInt},
			{"serv_urlchang_host_name", "ServUrlchangHostName", ftString},
			{"serv_urlchang_path_type", "ServUrlchangPathType", ftInt},
			{"serv_urlchang_path_match", "ServUrlchangPathMatch", ftString},
			{"serv_urlchang_page_name", "ServUrlchangPageName", ftString},
			{"serv_urlchang_page_type", "ServUrlchangPageType", ftString},
			{"serv_urlchang_actn_type", "ServUrlchangActnType", ftInt},
			{"serv_urlchang_path_insrt", "ServUrlchangPathInsrt", ftString},
			{"serv_urlchang_insrt_postn", "ServUrlchangInsrtPostn", ftInt},
			{"serv_urlchang_new_pg_name", "ServUrlchangNewPgName", ftString},
			{"serv_urlchang_new_pg_type", "ServUrlchangNewPgType", ftString},
			{"serv_path_hide_status", "ServPathHideStatus", ftInt},
			{"serv_path_hide_host_type", "ServPathHideHostType", ftInt},
			{"serv_path_hide_host_name", "ServPathHideHostName", ftString},
			{"serv_path_hide_path_type", "ServPathHidePathType", ftInt},
			{"serv_path_hide_path_name", "ServPathHidePathName", ftString},
			{"serv_textrep_status", "ServTextrepStatus", ftInt},
			{"serv_textrep_action", "ServTextrepAction", ftInt},
			{"serv_textrep_match_text", "ServTextrepMatchText", ftString},
			{"serv_textrep_replac_txt", "ServTextrepReplacTxt", ftString},
			{"serv_application_type", "ServApplicationType", ftInt},
			{"name", "Name", ftString},
			{"action", "Action", ftInt},
			{"redirect", "Redirect", ftString},
			{"serv_cert_grp_mark", "ServCertGrpMark", ftInt},
			{"dns_type", "DnsType", ftInt},
			{"clntprox_type", "ClntproxType", ftInt},
			{"zerowin_size", "ZerowinSize", ftInt},
			{"cookie_path", "CookiePath", ftString},
			{"cookie_secure", "CookieSecure", ftInt},
			{"no_rtsp", "NoRtsp", ftInt},
			{"ck_rebind", "CkRebind", ftInt},
			{"parse_limit", "ParseLimit", ftInt},
			{"parse_length", "ParseLength", ftInt},
			{"uri_norm", "UriNorm", ftInt},
			{"granularity", "Granularity", ftInt},
			{"sess_log", "SessLog", ftInt},
			{"udp_age", "UdpAge", ftInt},
			{"sess_entry_mode", "SessEntryMode", ftInt},
			{"sec_pol", "SecPol", ftString},
			{"always_on", "AlwaysOn", ftInt},
			{"send_rst", "SendRST", ftInt},
			{"cls_on_slowage", "ClsOnSlowage", ftInt},
			{"hname", "Hname", ftString},
			{"cname", "Cname", ftString},
			{"c_expire", "CExpire", ftString},
			{"url_hash_len", "UrlHashLen", ftInt},
			{"direct", "Direct", ftInt},
			{"thash", "Thash", ftInt},
			{"ldapreset", "Ldapreset", ftInt},
			{"ldapslb", "Ldapslb", ftInt},
			{"sip", "Sip", ftInt},
			{"x_forwarded_for", "XForwardedFor", ftInt},
			{"http_redir", "HttpRedir", ftInt},
			{"pbind_rport", "PbindRport", ftInt},
			{"egress_pip", "EgressPip", ftInt},
			{"cookie_dname", "CookieDname", ftInt},
			{"wts", "Wts", ftInt},
			{"uhash", "Uhash", ftInt},
			{"time_out", "TimeOut", ftInt},
			{"sdp_nat", "SdpNat", ftInt},
			{"real_group", "RealGroup", ftString},
			{"session_mirror", "SessionMirror", ftInt},
			{"soft_grid", "SoftGrid", ftInt},
			{"conn_pooling", "ConnPooling", ftInt},
			{"persistent_time_out", "PersistentTimeOut", ftInt},
			{"proxy_ip_mode", "ProxyIpMode", ftInt},
			{"proxy_ip_addr", "ProxyIpAddr", ftString},
			{"proxy_ip_mask", "ProxyIpMask", ftString},
			{"proxy_ipv6_addr", "ProxyIpv6Addr", ftString},
			{"proxy_ipv6_prefix", "ProxyIpv6Prefix", ftInt},
			{"proxy_ip_persistency", "ProxyIpPersistency", ftInt},
			{"proxy_ip_n_wclass", "ProxyIpNWclass", ftString},
			{"proxy_ipv6_n_wclass", "ProxyIpv6NWclass", ftString},
			{"proxy_ip_n_wclass_persistency", "ProxyIpNWclassPersistency", ftInt},
			{"hash_len", "HashLen", ftInt},
			{"cls_rst", "ClsRST", ftInt},
			{"http_hdr_name", "HttpHdrName", ftString},
			{"serv_fast_wa", "ServFastWa", ftString},
			{"appwall_webapp_id", "AppwallWebappId", ftString},
			{"http2", "Http2", ftString},
			{"cluster", "Cluster", ftInt},
			{"data_port", "DataPort", ftInt},
			{"applic_name", "ApplicName", ftString},
			{"report", "Report", ftInt},
			{"trevpol", "Trevpol", ftString},
			{"satisrt", "Satisrt", ftInt},
			{"namesrvr", "Namesrvr", ftString},
		},
	}
}
func resource_alteon_virtual_service() *schema.Resource {
	return flatResourceFromSpec(virtualServiceSpec())
}

// https_health_check: Die alte Ressource wird durch alteon_advhc_http ersetzt.
// Fuer Rueckwaertskompatibilitaet bleibt sie als Alias registriert und zeigt
// auf dieselbe AdvHC-HTTP-Implementierung.
func resource_alteon_https_health_check() *schema.Resource {
	return resource_alteon_advhc_http()
}

func filterSpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_filter",
		Tables:       []string{"fltNewCfgTable"},
		KeySchema:    "index",
		KeyType:      ftInt,
		KeyAPIs:      []string{"Indx"},
		Fields: []flatField{
			{"src_ip", "SrcIp", ftString},
			{"src_ip_mask", "SrcIpMask", ftString},
			{"dst_ip", "DstIp", ftString},
			{"dst_ip_mask", "DstIpMask", ftString},
			{"protocol", "Protocol", ftString},
			{"range_high_src_port", "RangeHighSrcPort", ftString},
			{"range_low_src_port", "RangeLowSrcPort", ftString},
			{"range_low_dst_port", "RangeLowDstPort", ftString},
			{"range_high_dst_port", "RangeHighDstPort", ftString},
			{"action", "Action", ftInt},
			{"redir_port", "RedirPort", ftString},
			{"redir_group", "RedirGroup", ftString},
			{"log", "Log", ftInt},
			{"state", "State", ftInt},
			{"nat", "Nat", ftInt},
			{"cache", "Cache", ftInt},
			{"invert", "Invert", ftInt},
			{"client_proxy", "ClientProxy", ftInt},
			{"tcp_ack", "TcpAck", ftInt},
			{"src_mac", "SrcMac", ftString},
			{"dst_mac", "DstMac", ftString},
			{"ftp_nat_active", "FtpNatActive", ftInt},
			{"acl_tcp_urg", "AclTcpUrg", ftInt},
			{"acl_tcp_ack", "AclTcpAck", ftInt},
			{"acl_tcp_psh", "AclTcpPsh", ftInt},
			{"acl_tcp_rst", "AclTcpRst", ftInt},
			{"acl_tcp_syn", "AclTcpSyn", ftInt},
			{"acl_tcp_fin", "AclTcpFin", ftInt},
			{"acl_icmp", "AclIcmp", ftString},
			{"acl_ip_option", "AclIpOption", ftInt},
			{"bwm_contract", "BwmContract", ftString},
			{"acl_ip_tos", "AclIpTos", ftString},
			{"acl_ip_tos_mask", "AclIpTosMask", ftString},
			{"acl_ip_tos_new", "AclIpTosNew", ftString},
			{"fwlb", "Fwlb", ftInt},
			{"nat_timeout", "NatTimeout", ftString},
			{"linklb", "Linklb", ftInt},
			{"wap_radius_snoop", "WapRadiusSnoop", ftInt},
			{"src_ip_mac", "SrcIpMac", ftInt},
			{"dst_ip_mac", "DstIpMac", ftInt},
			{"idslb_hash", "IdslbHash", ftInt},
			{"vlan", "Vlan", ftString},
			{"name", "Name", ftString},
			{"tcp_rate_limit", "TcpRateLimit", ftInt},
			{"tcp_rate_max_conn", "TcpRateMaxConn", ftString},
			{"hash", "Hash", ftInt},
			{"layer7_deny_state", "Layer7DenyState", ftInt},
			{"goto_filter", "GotoFilter", ftString},
			{"radius_wap_persist", "RadiusWapPersist", ftInt},
			{"pbind", "Pbind", ftInt},
			{"time_window", "TimeWindow", ftString},
			{"hold_duration", "HoldDuration", ftString},
			{"pattern_match", "PatternMatch", ftInt},
			{"layer7_deny_match_all", "Layer7DenyMatchAll", ftInt},
			{"proxy_ip", "ProxyIp", ftString},
			{"layer7_parse_all", "Layer7ParseAll", ftInt},
			{"security_parse_all", "SecurityParseAll", ftInt},
			{"cfg8021p_bits_value", "Cfg8021pBitsValue", ftString},
			{"cfg8021p_bits_match", "Cfg8021pBitsMatch", ftInt},
			{"acl_ip_length", "AclIpLength", ftString},
			{"ids_group", "IdsGroup", ftString},
			{"egress_pip", "EgressPip", ftInt},
			{"dbind", "Dbind", ftInt},
			{"rev_bwm_contract", "RevBwmContract", ftString},
			{"reverse", "Reverse", ftInt},
			{"parse_chn", "ParseChn", ftInt},
			{"rtp_bwm_contract", "RtpBwmContract", ftString},
			{"sip_parsing", "SipParsing", ftInt},
			{"session_mirror", "SessionMirror", ftInt},
			{"ip_ver", "IpVer", ftInt},
			{"ipv6_sip", "Ipv6Sip", ftString},
			{"ipv6_sprefix", "Ipv6Sprefix", ftString},
			{"ipv6_dip", "Ipv6Dip", ftString},
			{"ipv6_dprefix", "Ipv6Dprefix", ftString},
			{"hdr_hash", "HdrHash", ftInt},
			{"hdr_name", "HdrName", ftString},
			{"hdr_hash_len", "HdrHashLen", ftString},
			{"l3_filter", "L3Filter", ftInt},
			{"nat_ip", "NatIp", ftString},
			{"ipv6_nip", "Ipv6Nip", ftString},
			{"ipv6_proxy", "Ipv6Proxy", ftString},
			{"l7_sip_filt", "L7SipFilt", ftInt},
			{"nat_mcast_vlan", "NatMcastVlan", ftString},
			{"nbind", "Nbind", ftInt},
			{"layer7_invert_action", "Layer7InvertAction", ftInt},
			{"src_class_id", "SrcClassId", ftString},
			{"dst_class_id", "DstClassId", ftString},
			{"rtsrcmac", "Rtsrcmac", ftInt},
			{"rtproxy", "Rtproxy", ftInt},
			{"sesslog", "Sesslog", ftInt},
			{"cntclass", "Cntclass", ftString},
			{"applic_type", "ApplicType", ftInt},
			{"rtsport", "Rtsport", ftInt},
			{"src_addr_type", "SrcAddrType", ftInt},
			{"dst_addr_type", "DstAddrType", ftInt},
			{"cos_str", "CosStr", ftString},
			{"udp_age", "UdpAge", ftInt},
			{"fe_tcp_pol_id", "FeTcpPolId", ftString},
			{"be_tcp_pol_id", "BeTcpPolId", ftString},
			{"comppol", "Comppol", ftString},
			{"ssl_inspection_ena", "SslInspectionEna", ftInt},
			{"srv_cert_group", "SrvCertGroup", ftInt},
			{"srv_cert", "SrvCert", ftString},
			{"ssl_policy", "SslPolicy", ftString},
			{"match_dev", "MatchDev", ftInt},
			{"ssl_l7_action", "SslL7Action", ftInt},
			{"fallback", "Fallback", ftInt},
			{"fbgoto", "Fbgoto", ftString},
			{"vpn_flood", "VpnFlood", ftInt},
			{"url_flt_pol", "UrlFltPol", ftString},
			{"fbport", "Fbport", ftString},
			{"set_index", "SetIndex", ftString},
			{"mac_to_me", "MacToMe", ftInt},
			{"fbvlan", "Fbvlan", ftString},
			{"urlfmode", "Urlfmode", ftString},
			{"botpol", "Botpol", ftString},
			{"awinflow", "Awinflow", ftInt},
			{"srv_cert_enc", "SrvCertEnc", ftString},
			{"srv_cert_sign", "SrvCertSign", ftString},
			{"sideband_id", "SidebandID", ftString},
			{"secure_path_policy", "SecurePathPolicy", ftString},
			{"jsinject", "Jsinject", ftInt},
			{"aw_threshold_op", "AwThresholdOp", ftString},
			{"aw_mintrans_op", "AwMintransOp", ftString},
			{"req_headers_timeout", "ReqHeadersTimeout", ftString},
			{"segment_name", "SegmentName", ftString},
			{"vlangrp", "Vlangrp", ftString},
		},
	}
}
func resource_alteon_filter() *schema.Resource {
	return flatResourceFromSpec(filterSpec())
}

func sslCertSpec() flatSpec {
	return flatSpec{
		ResourceName: "alteon_ssl_cert",
		Tables:       []string{"slbNewSslCfgCertsTable"},
		KeySchema:    "cert_id",
		KeyType:      ftString,
		KeyAPIs:      []string{"ID", "Type"},
		Key2Schema:   "cert_type",
		Key2API:      "Type",
		Key2Type:     ftInt,
		Fields: []flatField{
			{"name", "Name", ftString},
			{"key_size", "KeySize", ftInt},
			{"expirty", "Expirty", ftString},
			{"common_name", "CommonName", ftString},
			{"hash_algo", "HashAlgo", ftInt},
			{"country_name", "CountryName", ftString},
			{"prpvince_name", "PrpvinceName", ftString},
			{"locality_name", "LocalityName", ftString},
			{"organization_name", "OrganizationName", ftString},
			{"organization_unit_name", "OrganizationUnitName", ftString},
			{"e_mail", "EMail", ftString},
			{"validity_period", "ValidityPeriod", ftInt},
			{"status", "Status", ftInt},
			{"key_type", "KeyType", ftInt},
			{"key_size_ec", "KeySizeEc", ftInt},
			{"curve_name_ec", "CurveNameEc", ftInt},
			{"key_size_common", "KeySizeCommon", ftInt},
			{"intermca_chain_name", "IntermcaChainName", ftString},
			{"intermca_chain_type", "IntermcaChainType", ftInt},
			{"serial", "Serial", ftString},
			{"subject_alt_name", "SubjectAltName", ftString},
			{"province_name", "ProvinceName", ftString},
			{"expiry", "Expiry", ftString},
		},
	}
}
func resource_alteon_ssl_cert() *schema.Resource {
	return flatResourceFromSpec(sslCertSpec())
}
